name: Pull Changes to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Write SSH Key to File
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Pull changes on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
        cd ~/officeBot || { echo "Directory not found!"; exit 1; }
        git pull origin main
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > ~/officeBot/.env
        chmod 600 ~/officeBot/.env
        sudo systemctl restart discordbot.service
        EOF
